### PR TITLE
Fix index out of bound issue

### PR DESCRIPTION
**Pull request by RensHam**

### CODE REVIEW

**Comment by pingiun** [comment]
I don't think this is necessary, does this fix a bug you encountered?

**Comment by RensHam** [comment]
This fixes index out of bound bug in group chat and fixes. In a group chat the bot tries to send a picture when there is a picture send to it. The bot will not say to many faces and still send a picture

**Comment by Taeir** [comment]
This small change ensures that the bot does not give an exception in group chats. I would like to see this implemented.

**Comment by pingiun** [comment]
Yes I see now

**Comment by pingiun** [comment]
@RensHam Why did you close this?

**Comment by RensHam** [comment]
See new pull request

**Pull request closed without merging**
